### ISSUE TITLE
Directory Extension issue

### ISSUE THREAD

**Issue by quintendewilde** [redFrik/supercolliderStandaloneRPI64#1]
Compiling directory './share/system/SCClassLibrary'
	Compiling directory './share/system/Extensions'
WARNING: Could not open directory: './share/user/Extensions'
	To resolve this, either create the directory or remove it from your compilation paths.
	
	
	How can I create this directory?

**Comment by redFrik** [comment]
just log in to your Raspberry Pi and create the directory there...
```
mkdir ~/supercolliderStandaloneRPI64/share/user/Extensions
```

(the problem is that github doesn't support empty directories and i didn't want to make a hidden dummy file.)

you can also remove share/user/Extensions from the file sclang.yaml if you don't plan to put anything in it.

**Comment by quintendewilde** [comment]
@redFrik Thanks

**I get this output now. I'm guessing I did it correctly. 
The SC3 plugins, do they come in this folder? Is there a guideline to install these?**

compiling class library...
	Found 867 primitives.
	Compiling directory '/home/myname/.local/share/SuperCollider/Extensions'
	Compiling directory './share/system/SCClassLibrary'
	Compiling directory './share/system/Extensions'
WARNING: Could not open directory: './share/user/Extensions'
	To resolve this, either create the directory or remove it from your compilation paths.

	numentries = 1284032 / 19902908 = 0.065
	5878 method selectors, 3386 classes
	method table size 20949840 bytes, big table size 159223264
	Number of Symbols 15238
	Byte Code Size 455274
	compiled 557 files in 1.18 seconds

Info: 7 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.08 seconds

**Comment by redFrik** [comment]
The _WARNING: Could not open directory: './share/user/Extensions'_ is a harmless warning. Don't worry about it.

sc3-plugins should be installed and working in this standalone. You can test it using this code...
```supercollider
s.boot;
{JPverb.ar(Dust.ar(1))}.play;
```

JPverb is in sc3-plugins.

**Comment by quintendewilde** [comment]
Hi maybe not for this issue. But when I try your snippet. I hear the code play, when I do it a few times after each other I get the bottom exception.
```

-> Synth('temp__4' : 1000)
-> Synth('temp__5' : 1001)
-> Synth('temp__6' : 1002)
-> Synth('temp__7' : 1003)

Server 'localhost' exited with exit code 0.
server 'localhost' disconnected shared memory interface
```

**Comment by redFrik** [comment]
yes, this is unrelated to this raspberry pi standalone.

but...
the same thing happens on my mac laptop.  supercollider server only has 8192 Kb of realtime memory as default and the JPverb plugin requires quite a lot.  so when you start several reverbs at the same time, the server eventually is out of memory and crashes.
the fix is to increase your server memory.  run this line before booting.
```supercollider
s.options.memSize= 65536*4;
```
or put it in your startup.scd file and then it'll always allocate some extra memory.
this is also mentioned in the JPverb helpfile.
